// Generated by CoffeeScript 1.12.7
(function() {
  var ForLoopCommand;

  ForLoopCommand = (function() {
    function ForLoopCommand(params, interpreter) {
      this.params = params;
      this.interpreter = interpreter;
      this.index = 0;
      this.pointer = interpreter.pointer;
      this.list = this.interpreter.listObjectOf(this.params.listVariable);
    }

    ForLoopCommand.prototype.condition = function() {
      var result;
      result = this.index < this.list.length;
      this.interpreter.setNumberValueTo(this.params.indexVariable, this.index);
      this.interpreter.setValueToVariable(this.params.elementVariable, this.params.elementType, this.list[this.index]);
      this.index++;
      return result;
    };

    return ForLoopCommand;

  })();

  gs.ForLoopCommand = ForLoopCommand;

}).call(this);
