// Generated by CoffeeScript 1.12.7
(function() {
  var Object_Text,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Object_Text = (function(superClass) {
    extend(Object_Text, superClass);

    Object_Text.objectCodecBlackList = ["parent"];


    /**
    * A game object used for custom texts in a scene.
    *
    * @module gs
    * @class Object_Text
    * @extends gs.Object_Visual
    * @memberof gs
    * @constructor
     */

    function Object_Text(data) {
      Object_Text.__super__.constructor.apply(this, arguments);

      /**
      * The object's bitmap used for visual presentation.
      * @property bitmap
      * @type gs.Bitmap
       */
      this.bitmap = null;

      /**
      * The font used for the text.
      * @property font
      * @type gs.Font
       */
      this.font = new Font(gs.Fonts.TEXT);

      /**
      * Indicates if word-wrap is enabled. If <b>true</b> line-breaks are automatically added.
      * @property wordWrap
      * @type boolean
       */
      this.wordWrap = false;

      /**
      * The domain the object belongs to.
      * @property domain
      * @type string
       */
      this.domain = "com.degica.vnm.default";

      /**
      * The object's source rectangle. It controls which part of the object's image is used
      * for visual presentation.
      * @property srcRect
      * @type gs.Rect
       */
      this.srcRect = new Rect();

      /**
      * The object's mask to execute masking-effects on it.
      * @property mask
      * @type gs.Mask
       */
      this.mask = new gs.Mask();

      /**
      * Indicates if the object's visual presentation should be mirrored horizontally.
      * @property mirror
      * @type boolean
       */
      this.mirror = false;

      /**
      * The text to display.
      * @property text
      * @type string
       */
      this.text = "";

      /**
      * The rotation-angle of the picture in degrees. The rotation center depends on the
      * anchor-point.
      * @property angle
      * @type number
       */
      this.angle = 0;

      /**
      * The color tone of the object used for the visual presentation.
      * @property tone
      * @type gs.Tone
       */
      this.tone = new Tone(0, 0, 0, 0);

      /**
      * The color of the object used for the visual presentation.
      * @property color
      * @type gs.Color
       */
      this.color = new Color(255, 255, 255, 0);

      /**
      * The text-renderer used to render the text.
      * @property textRenderer
      * @type gs.Component_TextRenderer
       */
      this.textRenderer = new gs.Component_TextRenderer();
      this.textRenderer.object = this;

      /**
      * The object's animator-component to execute different kind of animations like move, rotate, etc. on it.
      * @property animator
      * @type gs.Component_Animator
       */
      this.animator = new gs.Component_Animator();

      /**
      * The object's visual-component to display the game object on screen.
      * @property visual
      * @type gs.Component_Sprite
       */
      this.visual = new gs.Component_Sprite(false);

      /**
      * The object's behavior component for the text-specific behavior.
      * @property behavior
      * @type gs.Component_TextBehavior
       */
      this.behavior = new gs.Component_TextBehavior();
      this.addComponent(this.visual);
      this.addComponent(this.behavior);
      this.addComponent(this.animator);
      this.componentsFromDataBundle(data);
    }


    /**
    * Restores the game object from a data-bundle.
    *
    * @method restore
    * @param {Object} data - The data-bundle.
     */

    Object_Text.prototype.restore = function(data) {
      Object_Text.__super__.restore.call(this, data);
      this.srcRect = gs.Rect.fromObject(data.srcRect);
      return this.mask = gs.Mask.fromObject(data.mask);
    };


    /**
    * Serializes the object into a data-bundle.
    *
    * @method toDataBundle
    * @return {Object} The data-bundle.
     */

    Object_Text.prototype.toDataBundle = function() {
      var components, result;
      components = this.componentsToDataBundle(gs.Component_Animation);
      result = {
        components: components,
        dstRect: this.dstRect,
        srcRect: this.srcRect,
        opacity: this.opacity,
        origin: this.origin,
        offset: this.offset,
        anchor: this.anchor,
        zIndex: this.zIndex,
        mask: this.mask.toDataBundle(),
        motionBlur: this.motionBlur,
        zoom: this.zoom,
        angle: this.angle,
        mirror: this.mirror,
        text: this.text,
        formatting: this.formatting
      };
      return result;
    };

    return Object_Text;

  })(gs.Object_Visual);

  gs.Object_Text = Object_Text;

}).call(this);
